# Generated by Django 4.2.5 on 2023-10-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastrar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materia_prima',
            new_name='A',
        ),
    ]
