# Generated by Django 4.2.5 on 2023-10-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastrar', '0002_rename_materia_prima_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material_do_produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPoduto', models.IntegerField(verbose_name='IDdoProduto')),
                ('idMaterial', models.IntegerField(verbose_name='IDdoMaterial')),
                ('qunat', models.IntegerField(verbose_name='Quantidade')),
            ],
        ),
    ]
