# Generated by Django 4.2.5 on 2023-10-08 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastrar', '0003_material_do_produto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='A',
            new_name='Materia_prima',
        ),
    ]
