# Generated by Django 4.2.5 on 2023-10-08 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastrar', '0004_rename_a_materia_prima'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materia_prima',
            new_name='A',
        ),
    ]
