# Generated by Django 4.2.5 on 2023-10-08 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastrar', '0006_materia_prima'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A',
        ),
    ]
