# Generated by Django 4.2.5 on 2023-10-12 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastrar', '0009_alter_material_do_produto_idmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_do_produto',
            name='idMaterial',
            field=models.IntegerField(verbose_name='IDdoMaterial'),
        ),
        migrations.AlterField(
            model_name='material_do_produto',
            name='idPoduto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastrar.produto'),
        ),
    ]
