# Generated by Django 4.2.5 on 2023-10-12 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastrar', '0010_alter_material_do_produto_idmaterial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_do_produto',
            name='idMaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastrar.materia_prima'),
        ),
    ]
