# Generated by Django 4.2.5 on 2023-10-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastrar', '0011_alter_material_do_produto_idmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='precoAutomatico',
            field=models.CharField(default='nao', max_length=5, verbose_name='precoautomatico'),
            preserve_default=False,
        ),
    ]
