# Generated by Django 4.2.5 on 2023-10-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastrar', '0012_produto_precoautomatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='porcemPadrao',
            field=models.CharField(default='sim', max_length=5, verbose_name='porcemPadrao'),
            preserve_default=False,
        ),
    ]
