# Generated by Django 4.2.5 on 2023-10-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastrar', '0013_produto_porcempadrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='porcemLucro',
            field=models.FloatField(default=0.3, max_length=4, verbose_name='%'),
            preserve_default=False,
        ),
    ]
