# Generated by Django 4.2.5 on 2023-10-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastrar', '0014_produto_porcemlucro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='porcemLucro',
            field=models.IntegerField(max_length=4, verbose_name='%'),
        ),
    ]
