# Generated by Django 4.2.5 on 2023-10-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastrar', '0015_alter_produto_porcemlucro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='porcemLucro',
            field=models.IntegerField(verbose_name='%'),
        ),
    ]
